#
# Vivado (TM) v2015.2 (64-bit)
#
# test_tcl.tcl: Tcl script for re-creating project 'project_3'
#
# Generated by Vivado on Tue Oct 03 16:38:43 EDT 2017
# IP Build 1264090 on Wed Jun 24 14:22:01 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (test_tcl.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "~/hop/obfuscation/gatelib/Register.v"
#    "~/hop/obfuscation/gatelib/ShiftRegister.v"
#    "~/hop/obfuscation/oram/addr/PathGen.v"
#    "~/hop/obfuscation/gatelib/Gray2Bin.v"
#    "~/hop/obfuscation/gatelib/Counter.v"
#    "~/hop/obfuscation/oram/include/Const.vh"
#    "~/hop/obfuscation/gatelib/CountCompare.v"
#    "~/hop/obfuscation/gatelib/Bin2Gray.v"
#    "~/hop/obfuscation/gatelib/RAM.v"
#    "~/hop/obfuscation/gatelib/FIFORegControl.v"
#    "~/hop/obfuscation/gatelib/FIFOControl.v"
#    "~/hop/obfuscation/gatelib/CountAlarm.v"
#    "~/hop/obfuscation/oram/addr/BktIDGen.v"
#    "~/hop/obfuscation/oram/include/PathORAM.vh"
#    "~/hop/obfuscation/oram/encryption/rew/ROISeedGenerator.v"
#    "~/hop/obfuscation/oram/backend/REWStatCtr.v"
#    "~/hop/obfuscation/gatelib/Pipeline.v"
#    "~/hop/obfuscation/gatelib/FIFORegister.v"
#    "~/hop/obfuscation/gatelib/FIFORAM.v"
#    "~/hop/obfuscation/oram/include/DDR3SDRAMLocal.vh"
#    "~/hop/obfuscation/oram/integrity/old/SHA3Local.vh"
#    "~/hop/obfuscation/oram/include/BucketLocal.vh"
#    "~/hop/obfuscation/oram/backend/old/CoherenceController.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_rcon.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_sbox.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/table.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_key_expand_128.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/expand_key_128.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_cipher_top.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/padder1.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/round2in1.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/rconst2in1.v"
#    "~/hop/obfuscation/gatelib/Reverse.v"
#    "~/hop/obfuscation/gatelib/Mux.v"
#    "~/hop/obfuscation/gatelib/OneHot2Bin.v"
#    "~/hop/obfuscation/gatelib/UDCounter.v"
#    "~/hop/obfuscation/oram/include/StashLocal.vh"
#    "~/hop/obfuscation/oram/stash/StashScanTable.v"
#    "~/hop/obfuscation/oram/include/JTAG.vh"
#    "~/hop/obfuscation/oram/include/DMLocal.vh"
#    "~/hop/obfuscation/oram/include/CommandsLocal.vh"
#    "~/hop/obfuscation/oram/stash/StashCore.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/final_round.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/round.v"
#    "~/hop/obfuscation/oram/encryption/basic/AES_DW.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/padder.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/f_permutation.v"
#    "~/hop/obfuscation/gatelib/FIFOShiftRound.v"
#    "~/hop/obfuscation/oram/stash/Stash.v"
#    "~/hop/obfuscation/oram/stash/StashToDRAM.v"
#    "~/hop/obfuscation/oram/stash/DRAMToStash.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/aes_128.v"
#    "~/hop/obfuscation/oram/encryption/basic/PRNG.v"
#    "~/hop/obfuscation/oram/include/CacheCmdLocal.vh"
#    "~/hop/obfuscation/oram/include/CacheLocal.vh"
#    "~/hop/obfuscation/oram/frontend/DM_Cache.v"
#    "~/hop/obfuscation/oram/addr/AddrGenBktHead.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/keccak.v"
#    "~/hop/obfuscation/oram/include/TrafficGenLocal.vh"
#    "~/hop/obfuscation/oram/backend/BackendCoreController.v"
#    "~/hop/obfuscation/oram/stash/StashTop.v"
#    "~/hop/obfuscation/oram/include/REWAESLocal.vh"
#    "~/hop/obfuscation/oram/encryption/rew/REWAESCore.v"
#    "~/hop/obfuscation/oram/encryption/rew/GentrySeedGenerator.v"
#    "~/hop/obfuscation/oram/encryption/basic/AES_W.v"
#    "~/hop/obfuscation/oram/include/PLBLocal.vh"
#    "~/hop/obfuscation/oram/include/UORAM.vh"
#    "~/hop/obfuscation/oram/frontend/UORAMDataPath.v"
#    "~/hop/obfuscation/oram/frontend/PosMapPLB.v"
#    "~/hop/obfuscation/oram/addr/AddrGen.v"
#    "~/hop/obfuscation/oram/integrity/Keccak_WF.v"
#    "~/hop/obfuscation/gatelib/DRAM2RAM.v"
#    "~/hop/obfuscation/oram/include/IVLocal.vh"
#    "~/hop/obfuscation/oram/backend/PathORAMBackendCore.v"
#    "~/hop/obfuscation/oram/encryption/rew/AESREWORAM.v"
#    "~/hop/obfuscation/oram/encryption/basic/AESPathORAM.v"
#    "~/hop/obfuscation/oram/frontend/UORAMController.v"
#    "~/hop/obfuscation/oram/integrity/IntegrityVerifier.v"
#    "~/hop/obfuscation/gatelib/SynthesizedDRAM.v"
#    "~/hop/obfuscation/oram/backend/PathORAMBackend.v"
#    "~/hop/obfuscation/oram/frontend/Frontend.v"
#    "~/hop/obfuscation/gatelib/SynthesizedRandDRAM.v"
#    "~/hop/obfuscation/gatelib/ParityGen.v"
#    "~/hop/obfuscation/gatelib/LFSR.v"
#    "~/hop/obfuscation/gatelib/IORegister.v"
#    "~/hop/obfuscation/gatelib/FIFOLinear.v"
#    "~/hop/obfuscation/oram/ORAMWrap.v"
#    "~/hop/obfuscation/oram/TrafficGenASIC.v"
#    "~/hop/obfuscation/oram/TinyORAMCore.v"
#    "~/hop/obfuscation/oram/DummyGenASIC.v"
#    "~/hop/obfuscation/gatelib/UAReceiver.v"
#    "~/hop/obfuscation/gatelib/UATransmitter.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/timescale.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_inv_sbox.v"
#    "~/hop/obfuscation/oram/include/FSM.vh"
#    "~/hop/obfuscation/oram/Setup.v"
#    "~/hop/obfuscation/oram/ScratchPad.v"
#    "~/hop/obfuscation/oram/TinyORAMASICWrap.v"
#    "~/hop/obfuscation/oram/InstructionFilter.v"
#    "~/hop/obfuscation/oram/counter.v"
#    "~/hop/obfuscation/oram/ClipCmdValid.v"
#    "~/hop/obfuscation/gatelib/UART.v"
#    "~/hop/obfuscation/gatelib/ClockSource.v"
#    "~/hop/obfuscation/oram/Top.v"
#    "~/hop/obfuscation/oram/SetupWrap.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/aes_256.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/aes_192.v"
#    "~/hop/obfuscation/oram/encryption/rew/test/tiny_aes_vc707.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_inv_cipher_top.v"
#    "~/hop/obfuscation/gatelib/Debouncer.v"
#    "~/hop/obfuscation/gatelib/EdgeDetect.v"
#    "~/hop/obfuscation/gatelib/PulseExpander.v"
#    "~/hop/obfuscation/oram/testSetup.v"
#    "~/hop/obfuscation/oram/testSetupWrap.v"
#    "~/hop/obfuscation/oram/testCPU.v"
#    "~/hop/obfuscation/oram/backend/test/PathORAMBackendTestbench.v"
#    "~/hop/obfuscation/oram/stash/test/StashTestbench.v"
#    "~/hop/obfuscation/oram/shifter.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_endian.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_aes_256.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_aes_192.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_table_lookup.v"
#    "~/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_aes_128.v"
#    "~/hop/obfuscation/oram/encryption/rew/test/TinyAESTopTestbench.v"
#    "~/hop/obfuscation/oram/encryption/rew/test/REWAESCoreTestbench.v"
#    "~/hop/obfuscation/oram/encryption/rew/test/AESREWORAMTestbench.v"
#    "~/hop/obfuscation/oram/encryption/basic/core_ip/bench/verilog/test_bench_top.v"
#    "~/hop/obfuscation/oram/encryption/basic/test/AESDWTestBench.v"
#    "~/hop/obfuscation/oram/frontend/test/testUORAM_synthBackend.v"
#    "~/hop/obfuscation/oram/frontend/test/testPLB.v"
#    "~/hop/obfuscation/oram/frontend/test/testFrontEnd.v"
#    "~/hop/obfuscation/oram/frontend/test/testUORAM.v"
#    "~/hop/obfuscation/oram/addr/DRAMInitializer.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_f_permutation.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_padder1.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_keccak.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_padder.v"
#    "~/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_rconst2in1.v"
#    "~/hop/obfuscation/oram/integrity/old/IntegrityVerifier.v"
#    "~/hop/obfuscation/oram/integrity/test/testIntegrityVerifier.v"
#    "~/hop/obfuscation/gatelib/ButtonParse.v"
#    "~/hop/obfuscation/gatelib/Bin2HexASCII.v"
#    "~/hop/obfuscation/gatelib/DDR3SDRAM_mig7.v"
#    "~/hop/obfuscation/gatelib/PopAdd.v"
#    "~/hop/obfuscation/oram/stash/test/StashCoreTestbench.v"
#    "~/hop/obfuscation/oram/addr/SubTreeLocal.vh"
#    "~/hop/obfuscation/gatelib/Const.vh"
#    "~/hop/obfuscation/gatelib/PrioritySelect.v"
#    "~/project_3/testCPU_behav.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "../../"

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/hop/project_3"]"

# Create project
create_project project_3 $origin_dir/hop/project_3

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects project_3]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7a200tfbg676-2" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Register.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/ShiftRegister.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/addr/PathGen.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Gray2Bin.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Counter.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/Const.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/CountCompare.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Bin2Gray.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/RAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/FIFORegControl.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/FIFOControl.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/CountAlarm.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/addr/BktIDGen.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/PathORAM.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/ROISeedGenerator.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/backend/REWStatCtr.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Pipeline.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/FIFORegister.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/FIFORAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/DDR3SDRAMLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/old/SHA3Local.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/BucketLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/backend/old/CoherenceController.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_rcon.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_sbox.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/table.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_key_expand_128.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/expand_key_128.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_cipher_top.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/padder1.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/round2in1.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/rconst2in1.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Reverse.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Mux.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/OneHot2Bin.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/UDCounter.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/StashLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/StashScanTable.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/JTAG.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/DMLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/CommandsLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/StashCore.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/final_round.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/round.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/AES_DW.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/padder.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/f_permutation.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/FIFOShiftRound.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/Stash.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/StashToDRAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/DRAMToStash.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/aes_128.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/PRNG.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/CacheCmdLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/CacheLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/DM_Cache.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/addr/AddrGenBktHead.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/keccak.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/TrafficGenLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/backend/BackendCoreController.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/StashTop.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/REWAESLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/REWAESCore.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/GentrySeedGenerator.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/AES_W.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/PLBLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/UORAM.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/UORAMDataPath.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/PosMapPLB.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/addr/AddrGen.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/Keccak_WF.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/DRAM2RAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/IVLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/backend/PathORAMBackendCore.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/AESREWORAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/AESPathORAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/UORAMController.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/IntegrityVerifier.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/SynthesizedDRAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/backend/PathORAMBackend.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/Frontend.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/SynthesizedRandDRAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/ParityGen.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/LFSR.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/IORegister.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/FIFOLinear.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/ORAMWrap.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/TrafficGenASIC.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/TinyORAMCore.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/DummyGenASIC.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/UAReceiver.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/UATransmitter.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/timescale.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_inv_sbox.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/include/FSM.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/Setup.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/ScratchPad.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/TinyORAMASICWrap.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/InstructionFilter.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/counter.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/ClipCmdValid.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/UART.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/ClockSource.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/Top.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/SetupWrap.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/aes_256.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/aes_192.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/test/tiny_aes_vc707.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/rtl/verilog/aes_inv_cipher_top.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Debouncer.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/EdgeDetect.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/PulseExpander.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/testSetup.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/testSetupWrap.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/testCPU.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/backend/test/PathORAMBackendTestbench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/test/StashTestbench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/shifter.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_endian.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_aes_256.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_aes_192.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_table_lookup.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/core_ip/tiny_aes/test/test_aes_128.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/test/TinyAESTopTestbench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/test/REWAESCoreTestbench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/rew/test/AESREWORAMTestbench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/core_ip/bench/verilog/test_bench_top.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/encryption/basic/test/AESDWTestBench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/test/testUORAM_synthBackend.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/test/testPLB.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/test/testFrontEnd.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/frontend/test/testUORAM.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/addr/DRAMInitializer.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_f_permutation.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_padder1.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_keccak.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_padder.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/core_ip/Keccak512/test_rconst2in1.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/old/IntegrityVerifier.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/integrity/test/testIntegrityVerifier.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/ButtonParse.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Bin2HexASCII.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/DDR3SDRAM_mig7.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/PopAdd.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/stash/test/StashCoreTestbench.v"]"\
 "[file normalize "$origin_dir/hop/obfuscation/oram/addr/SubTreeLocal.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/Const.vh"]"\
 "[file normalize "$origin_dir/hop/obfuscation/gatelib/PrioritySelect.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hop/obfuscation/oram/include/Const.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/PathORAM.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/DDR3SDRAMLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/integrity/old/SHA3Local.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/BucketLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/StashLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/JTAG.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/DMLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/CommandsLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/CacheCmdLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/CacheLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/TrafficGenLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/REWAESLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/PLBLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/UORAM.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/IVLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/include/FSM.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/oram/addr/SubTreeLocal.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/hop/obfuscation/gatelib/Const.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "CoherenceController" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/hop/project_3/testCPU_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "testCPU" $obj
set_property "verilog_define" "MACROSAFE=1 SIMULATION_VIVADO=1 FPGA_MEMORY=1" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.simulate.runtime" "5ms" $obj
set_property "xsim.view" "$origin_dir/hop/project_3/testCPU_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a200tfbg676-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7a200tfbg676-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a200tfbg676-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7a200tfbg676-2" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:project_3"
